### ISSUE TITLE
Abstract Base Classes 

### ISSUE THREAD

**Issue by ayushkarnawat** [ayushkarnawat/profit#3]
According to [PEP 3119]( https://www.python.org/dev/peps/pep-3119/guidelines), we should be using abstract base classes (ABCs) for classes than need to be extended. 

For example, the base class `class BaseFileParser(object):` should be now `class BaseFileParser(ABC):` and proper decorators should be used, where necessary.

**Comment by karnawhat** [comment]
I believe this has been fixed, closing!
